url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Meu Teste Jekyll" # the name of your site, e.g. ACME Corp.
